version: '3'

services:
  postgresql:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: casino
      POSTGRES_PASSWORD: casino
      POSTGRES_DB: casinowars

  casinowars_server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
