/**
 * Poker wars sample implementation
 * This is a server implementation of Poker wars
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kaabab@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.casinowars.server.api.models


import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude

/**
 *
 * @param playerCard
 * @param casinoCard
 * @param result
 * @param tokenValue
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class BetResponse(
  val playerCard: Card? = null,
  val casinoCard: Card? = null,
  val result: BetResult? = null,
  val tokenValue: Int? = null
)

