/**
 * Poker wars sample implementation
 * This is a server implementation of Poker wars
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kaabab@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.casinowars.server.api.models


/**
 *
 * Values: win,war,loss,tiewin
 */
enum class BetResult(val value: String) {

  win("win"),

  war("war"),

  surrender("surrender"),

  loss("loss"),

  tiewin("tiewin");

}

